version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        description: Table which contains Airbnb listings details.
        identifier: raw_listings
      - name: hosts
        description: Table which contains Airbnb hosts details.
        identifier: raw_hosts
      - name: reviews
        description: Table which contains Airbnb reviews details.
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 1, period: hour}